
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GameConfig
{

public interface ITable
{
    void _LoadData();
}

public partial class Tables
{
    public UI.TbUIWnd TbUIWnd {get; }

    public Tables()
    {}
    
    private void ResolveRef()
    {}
}

}
