
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.UI
{
public sealed partial class UIWnd : Luban.BeanBase
{
    public UIWnd(ByteBuf _buf) 
    {
        Name = _buf.ReadString();
        Path = _buf.ReadString();
        Layer = _buf.ReadInt();
        DestroyOnHide = _buf.ReadBool();
    }

    public static UIWnd DeserializeUIWnd(ByteBuf _buf)
    {
        return new UI.UIWnd(_buf);
    }

    public readonly string Name;
    public readonly string Path;
    public readonly int Layer;
    public readonly bool DestroyOnHide;
   
    public const int __ID__ = -424015521;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef()
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Name:" + Name + ","
        + "Path:" + Path + ","
        + "Layer:" + Layer + ","
        + "DestroyOnHide:" + DestroyOnHide + ","
        + "}";
    }
}

}

