
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using TEngine.Localization.SimpleJSON;



namespace GameConfig.UI
{
public sealed partial class UIWnd : Luban.BeanBase
{
    public UIWnd(JSONNode _buf) 
    {
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Path"].IsString) { throw new SerializationException(); }  Path = _buf["Path"]; }
        { if(!_buf["Layer"].IsNumber) { throw new SerializationException(); }  Layer = _buf["Layer"]; }
        { if(!_buf["DestroyOnHide"].IsBoolean) { throw new SerializationException(); }  DestroyOnHide = _buf["DestroyOnHide"]; }
    }

    public static UIWnd DeserializeUIWnd(JSONNode _buf)
    {
        return new UI.UIWnd(_buf);
    }

    public readonly string Name;
    public readonly string Path;
    public readonly int Layer;
    public readonly bool DestroyOnHide;
   
    public const int __ID__ = -424015521;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef()
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Name:" + Name + ","
        + "Path:" + Path + ","
        + "Layer:" + Layer + ","
        + "DestroyOnHide:" + DestroyOnHide + ","
        + "}";
    }
}

}

