
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using UnityEngine;


namespace GameConfig.UI
{
public partial class TbUIWnd : ITable
{
    private readonly System.Collections.Generic.Dictionary<string, UI.UIWnd> _dataMap;
    private readonly System.Collections.Generic.List<UI.UIWnd> _dataList;
    
    public TbUIWnd()
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, UI.UIWnd>();
        _dataList = new System.Collections.Generic.List<UI.UIWnd>();
    }

    public System.Collections.Generic.Dictionary<string, UI.UIWnd> DataMap => _dataMap;
    public System.Collections.Generic.List<UI.UIWnd> DataList => _dataList;

    public UI.UIWnd GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public UI.UIWnd Get(string key) => _dataMap[key];
    public UI.UIWnd this[string key] => _dataMap[key];


    public void _LoadData()
    {
        ByteBuf _buf = LoadByteBuf("ui_tbuiwnd");
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            UI.UIWnd _v;
            _v = UI.UIWnd.DeserializeUIWnd(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Name, _v);
            _v.ResolveRef();
        }
    }

    /// <summary>
    /// 加载二进制配置。
    /// </summary>
    /// <param name="file">FileName</param>
    /// <returns>ByteBuf</returns>
    private ByteBuf LoadByteBuf(string fileName)
    {
        TextAsset textAsset = GameModule.Resource.LoadAsset<TextAsset>($"Config/bytes/{fileName}");
        byte[] bytes = textAsset.bytes;
        return new ByteBuf(bytes);
    }
}

}

