
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;



namespace GameConfig.PFGAS
{
/// <summary>
/// 定义 PFGAS 运行时使用的标签节点。
/// </summary>
public sealed partial class PFTag : Luban.BeanBase
{
    public PFTag(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["ParentId"].IsNumber) { throw new SerializationException(); }  ParentId = _buf["ParentId"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Desc"].IsString) { throw new SerializationException(); }  Desc = _buf["Desc"]; }
    }

    public static PFTag DeserializePFTag(JSONNode _buf)
    {
        return new PFGAS.PFTag(_buf);
    }

    /// <summary>
    /// 全局唯一 Tag ID。
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 父级 Tag ID；根节点填 -1。
    /// </summary>
    public readonly int ParentId;
    /// <summary>
    /// 同一父级下唯一，用于生成完整路径。
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// Tag 的用途说明，供编辑器和文档展示。
    /// </summary>
    public readonly string Desc;
   
    public const int __ID__ = 1281395993;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef()
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ParentId:" + ParentId + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "}";
    }
}

}

