
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using UnityEngine;
using TEngine.Localization.SimpleJSON;


namespace GameConfig.UI
{
public partial class TbUIWnd : ITable
{
    private readonly System.Collections.Generic.Dictionary<string, UI.UIWnd> _dataMap;
    private readonly System.Collections.Generic.List<UI.UIWnd> _dataList;
    
    public TbUIWnd()
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, UI.UIWnd>();
        _dataList = new System.Collections.Generic.List<UI.UIWnd>();
    }

    public System.Collections.Generic.Dictionary<string, UI.UIWnd> DataMap => _dataMap;
    public System.Collections.Generic.List<UI.UIWnd> DataList => _dataList;

    public UI.UIWnd GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public UI.UIWnd Get(string key) => _dataMap[key];
    public UI.UIWnd this[string key] => _dataMap[key];


    public void _LoadData()
    {
        
        JSONNode _buf = JSON.Parse(GetJson("ui_tbuiwnd"));
        foreach(JSONNode _ele in _buf.Children)
        {
            UI.UIWnd _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::GameConfig.UI.UIWnd.DeserializeUIWnd(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Name, _v);
            _v.ResolveRef();
        }
    }

    private string GetJson(string fileName)
    {
        var textAsset = GameModule.Resource.LoadAsset<TextAsset>(fileName);
        return textAsset.text;
    }
}

}

