
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using TEngine.Localization.SimpleJSON;



namespace GameConfig
{
public sealed partial class CommonSkill : Luban.BeanBase
{
    public CommonSkill(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["BuffName"].IsString) { throw new SerializationException(); }  BuffName = _buf["BuffName"]; }
        { if(!_buf["BuffDes"].IsString) { throw new SerializationException(); }  BuffDes = _buf["BuffDes"]; }
        { var __json0 = _buf["CurrentConstantId"]; if(!__json0.IsArray) { throw new SerializationException(); } CurrentConstantId = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  CurrentConstantId.Add(__v0); }   }
        { if(!_buf["PrefabPath"].IsString) { throw new SerializationException(); }  PrefabPath = _buf["PrefabPath"]; }
    }

    public static CommonSkill DeserializeCommonSkill(JSONNode _buf)
    {
        return new CommonSkill(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// buff枚举多语言Id
    /// </summary>
    public readonly string BuffName;
    /// <summary>
    /// buff描述多语言
    /// </summary>
    public readonly string BuffDes;
    public readonly System.Collections.Generic.List<int> CurrentConstantId;
    public readonly string PrefabPath;
   
    public const int __ID__ = -268250362;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef()
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "BuffName:" + BuffName + ","
        + "BuffDes:" + BuffDes + ","
        + "CurrentConstantId:" + Luban.StringUtil.CollectionToString(CurrentConstantId) + ","
        + "PrefabPath:" + PrefabPath + ","
        + "}";
    }
}

}

