
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using TEngine.Localization.SimpleJSON;



namespace GameConfig
{
public sealed partial class Condition : Luban.BeanBase
{
    public Condition(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
    }

    public static Condition DeserializeCondition(JSONNode _buf)
    {
        return new Condition(_buf);
    }

    public readonly int Id;
   
    public const int __ID__ = 1142656251;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef()
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "}";
    }
}

}

