
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using TEngine.Localization.SimpleJSON;



namespace GameConfig
{
public sealed partial class EnemyAttr : Luban.BeanBase
{
    public EnemyAttr(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Prefab"].IsString) { throw new SerializationException(); }  Prefab = _buf["Prefab"]; }
        { if(!_buf["Health"].IsNumber) { throw new SerializationException(); }  Health = _buf["Health"]; }
        { if(!_buf["Damage"].IsNumber) { throw new SerializationException(); }  Damage = _buf["Damage"]; }
        { if(!_buf["DamageBonus"].IsNumber) { throw new SerializationException(); }  DamageBonus = _buf["DamageBonus"]; }
        { if(!_buf["DamageReduction"].IsNumber) { throw new SerializationException(); }  DamageReduction = _buf["DamageReduction"]; }
        { if(!_buf["AttackSpeed"].IsNumber) { throw new SerializationException(); }  AttackSpeed = _buf["AttackSpeed"]; }
        { if(!_buf["CriticalStrikeChance"].IsNumber) { throw new SerializationException(); }  CriticalStrikeChance = _buf["CriticalStrikeChance"]; }
        { if(!_buf["CriticalBonus"].IsNumber) { throw new SerializationException(); }  CriticalBonus = _buf["CriticalBonus"]; }
        { if(!_buf["MoveSpeed"].IsNumber) { throw new SerializationException(); }  MoveSpeed = _buf["MoveSpeed"]; }
    }

    public static EnemyAttr DeserializeEnemyAttr(JSONNode _buf)
    {
        return new EnemyAttr(_buf);
    }

    /// <summary>
    /// 怪物ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 怪物名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 预制体路径
    /// </summary>
    public readonly string Prefab;
    /// <summary>
    /// 最大生命
    /// </summary>
    public readonly int Health;
    /// <summary>
    /// 基础伤害
    /// </summary>
    public readonly int Damage;
    /// <summary>
    /// 伤害加成
    /// </summary>
    public readonly int DamageBonus;
    /// <summary>
    /// 伤害减免
    /// </summary>
    public readonly int DamageReduction;
    /// <summary>
    /// 攻速
    /// </summary>
    public readonly int AttackSpeed;
    /// <summary>
    /// 暴击几率
    /// </summary>
    public readonly int CriticalStrikeChance;
    /// <summary>
    /// 暴击伤害加成
    /// </summary>
    public readonly int CriticalBonus;
    /// <summary>
    /// 移速
    /// </summary>
    public readonly int MoveSpeed;
   
    public const int __ID__ = 953235833;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef()
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Prefab:" + Prefab + ","
        + "Health:" + Health + ","
        + "Damage:" + Damage + ","
        + "DamageBonus:" + DamageBonus + ","
        + "DamageReduction:" + DamageReduction + ","
        + "AttackSpeed:" + AttackSpeed + ","
        + "CriticalStrikeChance:" + CriticalStrikeChance + ","
        + "CriticalBonus:" + CriticalBonus + ","
        + "MoveSpeed:" + MoveSpeed + ","
        + "}";
    }
}

}

