
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using TEngine.Localization.SimpleJSON;



namespace GameConfig
{
public sealed partial class EnemyGroup : Luban.BeanBase
{
    public EnemyGroup(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { var __json0 = _buf["UnitIds"]; if(!__json0.IsArray) { throw new SerializationException(); } UnitIds = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  UnitIds.Add(__v0); }   }
        { if(!_buf["EnemySpawnConditionType"].IsNumber) { throw new SerializationException(); }  EnemySpawnConditionType = _buf["EnemySpawnConditionType"]; }
        { if(!_buf["SpawnConditionValue"].IsNumber) { throw new SerializationException(); }  SpawnConditionValue = _buf["SpawnConditionValue"]; }
        { if(!_buf["SpawnChance"].IsNumber) { throw new SerializationException(); }  SpawnChance = _buf["SpawnChance"]; }
        { if(!_buf["SpawnTiming"].IsNumber) { throw new SerializationException(); }  SpawnTiming = _buf["SpawnTiming"]; }
        { if(!_buf["Repeating"].IsNumber) { throw new SerializationException(); }  Repeating = _buf["Repeating"]; }
        { if(!_buf["RepeatingTnterval"].IsNumber) { throw new SerializationException(); }  RepeatingTnterval = _buf["RepeatingTnterval"]; }
        { if(!_buf["RepeatingIntervalReduce"].IsNumber) { throw new SerializationException(); }  RepeatingIntervalReduce = _buf["RepeatingIntervalReduce"]; }
        { if(!_buf["RepeatingIntervalMin"].IsNumber) { throw new SerializationException(); }  RepeatingIntervalMin = _buf["RepeatingIntervalMin"]; }
        { if(!_buf["EnemySpawnLocationType"].IsNumber) { throw new SerializationException(); }  EnemySpawnLocationType = _buf["EnemySpawnLocationType"]; }
        { if(!_buf["SpwanDistAwayFromEdges"].IsNumber) { throw new SerializationException(); }  SpwanDistAwayFromEdges = _buf["SpwanDistAwayFromEdges"]; }
        { if(!_buf["SpwanEdgeOfMap"].IsBoolean) { throw new SerializationException(); }  SpwanEdgeOfMap = _buf["SpwanEdgeOfMap"]; }
        { if(!_buf["Area"].IsNumber) { throw new SerializationException(); }  Area = _buf["Area"]; }
    }

    public static EnemyGroup DeserializeEnemyGroup(JSONNode _buf)
    {
        return new EnemyGroup(_buf);
    }

    /// <summary>
    /// 组id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 组名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 候选单位id集合
    /// </summary>
    public readonly System.Collections.Generic.List<int> UnitIds;
    /// <summary>
    /// 怪物生成条件类型
    /// </summary>
    public readonly int EnemySpawnConditionType;
    /// <summary>
    /// 怪物生成阈值
    /// </summary>
    public readonly int SpawnConditionValue;
    /// <summary>
    /// 生成概率
    /// </summary>
    public readonly int SpawnChance;
    /// <summary>
    /// 生成时间
    /// </summary>
    public readonly int SpawnTiming;
    /// <summary>
    /// 重复生成次数
    /// </summary>
    public readonly int Repeating;
    /// <summary>
    /// 重复生成间隔
    /// </summary>
    public readonly float RepeatingTnterval;
    /// <summary>
    /// 重复间隔的递减值
    /// </summary>
    public readonly float RepeatingIntervalReduce;
    /// <summary>
    /// 重复间隔的最小值
    /// </summary>
    public readonly float RepeatingIntervalMin;
    /// <summary>
    /// 生成位置类型
    /// </summary>
    public readonly int EnemySpawnLocationType;
    /// <summary>
    /// 与地图边缘的最小距离
    /// </summary>
    public readonly int SpwanDistAwayFromEdges;
    /// <summary>
    /// 是否在地图边缘生成
    /// </summary>
    public readonly bool SpwanEdgeOfMap;
    /// <summary>
    /// 生成区域半径
    /// </summary>
    public readonly int Area;
   
    public const int __ID__ = -508983305;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef()
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "UnitIds:" + Luban.StringUtil.CollectionToString(UnitIds) + ","
        + "EnemySpawnConditionType:" + EnemySpawnConditionType + ","
        + "SpawnConditionValue:" + SpawnConditionValue + ","
        + "SpawnChance:" + SpawnChance + ","
        + "SpawnTiming:" + SpawnTiming + ","
        + "Repeating:" + Repeating + ","
        + "RepeatingTnterval:" + RepeatingTnterval + ","
        + "RepeatingIntervalReduce:" + RepeatingIntervalReduce + ","
        + "RepeatingIntervalMin:" + RepeatingIntervalMin + ","
        + "EnemySpawnLocationType:" + EnemySpawnLocationType + ","
        + "SpwanDistAwayFromEdges:" + SpwanDistAwayFromEdges + ","
        + "SpwanEdgeOfMap:" + SpwanEdgeOfMap + ","
        + "Area:" + Area + ","
        + "}";
    }
}

}

