
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using TEngine.Localization.SimpleJSON;



namespace GameConfig
{
public sealed partial class EnemyUnit : Luban.BeanBase
{
    public EnemyUnit(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["EnemyId"].IsNumber) { throw new SerializationException(); }  EnemyId = _buf["EnemyId"]; }
        { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = _buf["Type"]; }
        { if(!_buf["MinNum"].IsNumber) { throw new SerializationException(); }  MinNum = _buf["MinNum"]; }
        { if(!_buf["MaxNum"].IsNumber) { throw new SerializationException(); }  MaxNum = _buf["MaxNum"]; }
        { if(!_buf["SpawnChance"].IsNumber) { throw new SerializationException(); }  SpawnChance = _buf["SpawnChance"]; }
    }

    public static EnemyUnit DeserializeEnemyUnit(JSONNode _buf)
    {
        return new EnemyUnit(_buf);
    }

    /// <summary>
    /// 怪物单位ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 怪物单位名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 怪物Id
    /// </summary>
    public readonly int EnemyId;
    /// <summary>
    /// 怪物类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 最小生成数量
    /// </summary>
    public readonly int MinNum;
    /// <summary>
    /// 最大生成数量
    /// </summary>
    public readonly int MaxNum;
    /// <summary>
    /// 生成概率
    /// </summary>
    public readonly int SpawnChance;
   
    public const int __ID__ = 953825548;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef()
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "EnemyId:" + EnemyId + ","
        + "Type:" + Type + ","
        + "MinNum:" + MinNum + ","
        + "MaxNum:" + MaxNum + ","
        + "SpawnChance:" + SpawnChance + ","
        + "}";
    }
}

}

