
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using TEngine.Localization.SimpleJSON;



namespace GameConfig
{
public sealed partial class RoleBuff : Luban.BeanBase
{
    public RoleBuff(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["BuffName"].IsString) { throw new SerializationException(); }  BuffName = _buf["BuffName"]; }
        { if(!_buf["ShowType"].IsNumber) { throw new SerializationException(); }  ShowType = _buf["ShowType"]; }
        { if(!_buf["BuffDes"].IsString) { throw new SerializationException(); }  BuffDes = _buf["BuffDes"]; }
        { if(!_buf["IconPath"].IsString) { throw new SerializationException(); }  IconPath = _buf["IconPath"]; }
    }

    public static RoleBuff DeserializeRoleBuff(JSONNode _buf)
    {
        return new RoleBuff(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// buff枚举多语言Id
    /// </summary>
    public readonly string BuffName;
    public readonly int ShowType;
    /// <summary>
    /// buff描述多语言
    /// </summary>
    public readonly string BuffDes;
    public readonly string IconPath;
   
    public const int __ID__ = -202473975;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef()
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "BuffName:" + BuffName + ","
        + "ShowType:" + ShowType + ","
        + "BuffDes:" + BuffDes + ","
        + "IconPath:" + IconPath + ","
        + "}";
    }
}

}

