
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using TEngine.Localization.SimpleJSON;



namespace GameConfig
{
public sealed partial class RoleSkill : Luban.BeanBase
{
    public RoleSkill(JSONNode _buf) 
    {
        { if(!_buf["Key"].IsNumber) { throw new SerializationException(); }  Key = _buf["Key"]; }
        { if(!_buf["SkillName"].IsString) { throw new SerializationException(); }  SkillName = _buf["SkillName"]; }
        { if(!_buf["Note1"].IsString) { throw new SerializationException(); }  Note1 = _buf["Note1"]; }
        { if(!_buf["SkillDes"].IsString) { throw new SerializationException(); }  SkillDes = _buf["SkillDes"]; }
        { if(!_buf["Note2"].IsString) { throw new SerializationException(); }  Note2 = _buf["Note2"]; }
        { if(!_buf["Duration"].IsNumber) { throw new SerializationException(); }  Duration = _buf["Duration"]; }
        { if(!_buf["PassiveCooling"].IsNumber) { throw new SerializationException(); }  PassiveCooling = _buf["PassiveCooling"]; }
        { var __json0 = _buf["TextValue"]; if(!__json0.IsArray) { throw new SerializationException(); } TextValue = new System.Collections.Generic.List<System.Collections.Generic.List<float>>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { System.Collections.Generic.List<float> __v0;  { var __json1 = __e0; if(!__json1.IsArray) { throw new SerializationException(); } __v0 = new System.Collections.Generic.List<float>(__json1.Count); foreach(JSONNode __e1 in __json1.Children) { float __v1;  { if(!__e1.IsNumber) { throw new SerializationException(); }  __v1 = __e1; }  __v0.Add(__v1); }   }  TextValue.Add(__v0); }   }
        { if(!_buf["Tag"].IsNumber) { throw new SerializationException(); }  Tag = _buf["Tag"]; }
        { if(!_buf["Distortion"].IsNumber) { throw new SerializationException(); }  Distortion = _buf["Distortion"]; }
        { if(!_buf["IconPath"].IsString) { throw new SerializationException(); }  IconPath = _buf["IconPath"]; }
        { if(!_buf["PassiveSkillDes"].IsString) { throw new SerializationException(); }  PassiveSkillDes = _buf["PassiveSkillDes"]; }
    }

    public static RoleSkill DeserializeRoleSkill(JSONNode _buf)
    {
        return new RoleSkill(_buf);
    }

    public readonly int Key;
    /// <summary>
    /// 道种名称
    /// </summary>
    public readonly string SkillName;
    /// <summary>
    /// 备注1
    /// </summary>
    public readonly string Note1;
    /// <summary>
    /// 技能描述
    /// </summary>
    public readonly string SkillDes;
    /// <summary>
    /// 备注2
    /// </summary>
    public readonly string Note2;
    /// <summary>
    /// 主动技能持续时长
    /// </summary>
    public readonly float Duration;
    /// <summary>
    /// 被动冷却时长
    /// </summary>
    public readonly float PassiveCooling;
    /// <summary>
    /// 技能描述参数
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<float>> TextValue;
    /// <summary>
    /// 标签
    /// </summary>
    public readonly int Tag;
    /// <summary>
    /// 畸变道种Key
    /// </summary>
    public readonly int Distortion;
    public readonly string IconPath;
    public readonly string PassiveSkillDes;
   
    public const int __ID__ = -1966320805;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef()
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Key:" + Key + ","
        + "SkillName:" + SkillName + ","
        + "Note1:" + Note1 + ","
        + "SkillDes:" + SkillDes + ","
        + "Note2:" + Note2 + ","
        + "Duration:" + Duration + ","
        + "PassiveCooling:" + PassiveCooling + ","
        + "TextValue:" + Luban.StringUtil.CollectionToString(TextValue) + ","
        + "Tag:" + Tag + ","
        + "Distortion:" + Distortion + ","
        + "IconPath:" + IconPath + ","
        + "PassiveSkillDes:" + PassiveSkillDes + ","
        + "}";
    }
}

}

