
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using TEngine.Localization.SimpleJSON;



namespace GameConfig
{
public sealed partial class RoleStat : Luban.BeanBase
{
    public RoleStat(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["StatName"].IsString) { throw new SerializationException(); }  StatName = _buf["StatName"]; }
        { if(!_buf["ShowType"].IsNumber) { throw new SerializationException(); }  ShowType = _buf["ShowType"]; }
        { var __json0 = _buf["Role"]; if(!__json0.IsArray) { throw new SerializationException(); } Role = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Role.Add(__v0); }   }
        { if(!_buf["Percentage"].IsNumber) { throw new SerializationException(); }  Percentage = _buf["Percentage"]; }
        { if(!_buf["Sort"].IsNumber) { throw new SerializationException(); }  Sort = _buf["Sort"]; }
        { if(!_buf["StatType"].IsNumber) { throw new SerializationException(); }  StatType = _buf["StatType"]; }
        { if(!_buf["StatTypeDes"].IsString) { throw new SerializationException(); }  StatTypeDes = _buf["StatTypeDes"]; }
    }

    public static RoleStat DeserializeRoleStat(JSONNode _buf)
    {
        return new RoleStat(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 属性枚举多语言Id
    /// </summary>
    public readonly string StatName;
    public readonly int ShowType;
    /// <summary>
    /// 角色初始属性
    /// </summary>
    public readonly System.Collections.Generic.List<int> Role;
    public readonly int Percentage;
    /// <summary>
    /// 排列顺序
    /// </summary>
    public readonly int Sort;
    public readonly int StatType;
    /// <summary>
    /// 属性类型归类名
    /// </summary>
    public readonly string StatTypeDes;
   
    public const int __ID__ = -201968630;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef()
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "StatName:" + StatName + ","
        + "ShowType:" + ShowType + ","
        + "Role:" + Luban.StringUtil.CollectionToString(Role) + ","
        + "Percentage:" + Percentage + ","
        + "Sort:" + Sort + ","
        + "StatType:" + StatType + ","
        + "StatTypeDes:" + StatTypeDes + ","
        + "}";
    }
}

}

