
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using TEngine.Localization.SimpleJSON;



namespace GameConfig
{
public sealed partial class RoleTrait : Luban.BeanBase
{
    public RoleTrait(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Color"].IsString) { throw new SerializationException(); }  Color = _buf["Color"]; }
        { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = _buf["Type"]; }
        { if(!_buf["IconPath"].IsString) { throw new SerializationException(); }  IconPath = _buf["IconPath"]; }
        { var __json0 = _buf["Grade"]; if(!__json0.IsArray) { throw new SerializationException(); } Grade = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Grade.Add(__v0); }   }
        { var __json0 = _buf["TraitTime"]; if(!__json0.IsArray) { throw new SerializationException(); } TraitTime = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  TraitTime.Add(__v0); }   }
        { var __json0 = _buf["Des"]; if(!__json0.IsArray) { throw new SerializationException(); } Des = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  Des.Add(__v0); }   }
    }

    public static RoleTrait DeserializeRoleTrait(JSONNode _buf)
    {
        return new RoleTrait(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 羁绊名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 颜色
    /// </summary>
    public readonly string Color;
    public readonly int Type;
    public readonly string IconPath;
    /// <summary>
    /// 羁绊的等级
    /// </summary>
    public readonly System.Collections.Generic.List<int> Grade;
    /// <summary>
    /// 羁绊技能的冷却时间
    /// </summary>
    public readonly System.Collections.Generic.List<int> TraitTime;
    /// <summary>
    /// 羁绊描述
    /// </summary>
    public readonly System.Collections.Generic.List<string> Des;
   
    public const int __ID__ = -1965196520;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef()
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Color:" + Color + ","
        + "Type:" + Type + ","
        + "IconPath:" + IconPath + ","
        + "Grade:" + Luban.StringUtil.CollectionToString(Grade) + ","
        + "TraitTime:" + Luban.StringUtil.CollectionToString(TraitTime) + ","
        + "Des:" + Luban.StringUtil.CollectionToString(Des) + ","
        + "}";
    }
}

}

