
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using TEngine.Localization.SimpleJSON;



namespace GameConfig
{
public sealed partial class StatAugmentsData : Luban.BeanBase
{
    public StatAugmentsData(JSONNode _buf) 
    {
        { if(!_buf["Key"].IsNumber) { throw new SerializationException(); }  Key = _buf["Key"]; }
        { if(!_buf["StatType"].IsNumber) { throw new SerializationException(); }  StatType = _buf["StatType"]; }
        { if(!_buf["Tag"].IsNumber) { throw new SerializationException(); }  Tag = _buf["Tag"]; }
        { if(!_buf["Rarity"].IsNumber) { throw new SerializationException(); }  Rarity = _buf["Rarity"]; }
        { if(!_buf["AddType"].IsNumber) { throw new SerializationException(); }  AddType = _buf["AddType"]; }
        { if(!_buf["MinValue"].IsNumber) { throw new SerializationException(); }  MinValue = _buf["MinValue"]; }
        { if(!_buf["MaxValue"].IsNumber) { throw new SerializationException(); }  MaxValue = _buf["MaxValue"]; }
    }

    public static StatAugmentsData DeserializeStatAugmentsData(JSONNode _buf)
    {
        return new StatAugmentsData(_buf);
    }

    public readonly int Key;
    /// <summary>
    /// 属性枚举
    /// </summary>
    public readonly int StatType;
    /// <summary>
    /// 标签
    /// </summary>
    public readonly int Tag;
    /// <summary>
    /// 稀有度
    /// </summary>
    public readonly int Rarity;
    /// <summary>
    /// 属性加成类型
    /// </summary>
    public readonly int AddType;
    /// <summary>
    /// 属性加成值（最小范围）
    /// </summary>
    public readonly int MinValue;
    /// <summary>
    /// 属性加成值（最大范围）
    /// </summary>
    public readonly int MaxValue;
   
    public const int __ID__ = 1889216352;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef()
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Key:" + Key + ","
        + "StatType:" + StatType + ","
        + "Tag:" + Tag + ","
        + "Rarity:" + Rarity + ","
        + "AddType:" + AddType + ","
        + "MinValue:" + MinValue + ","
        + "MaxValue:" + MaxValue + ","
        + "}";
    }
}

}

