
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using TEngine.Localization.SimpleJSON;



namespace GameConfig
{
public sealed partial class TableHextech : Luban.BeanBase
{
    public TableHextech(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Level"].IsNumber) { throw new SerializationException(); }  Level = _buf["Level"]; }
        { if(!_buf["Des"].IsString) { throw new SerializationException(); }  Des = _buf["Des"]; }
        { var __json0 = _buf["EffectIds"]; if(!__json0.IsArray) { throw new SerializationException(); } EffectIds = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  EffectIds.Add(__v0); }   }
        { if(!_buf["ImagePath"].IsString) { throw new SerializationException(); }  ImagePath = _buf["ImagePath"]; }
        { if(!_buf["Frequency"].IsNumber) { throw new SerializationException(); }  Frequency = _buf["Frequency"]; }
    }

    public static TableHextech DeserializeTableHextech(JSONNode _buf)
    {
        return new TableHextech(_buf);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 海克斯名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 海克斯稀有度
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 海克斯描述
    /// </summary>
    public readonly string Des;
    /// <summary>
    /// 效果Id
    /// </summary>
    public readonly System.Collections.Generic.List<int> EffectIds;
    /// <summary>
    /// 图片路径
    /// </summary>
    public readonly string ImagePath;
    /// <summary>
    /// 海克斯一局出现次数
    /// </summary>
    public readonly int Frequency;
   
    public const int __ID__ = -1850721117;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef()
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Level:" + Level + ","
        + "Des:" + Des + ","
        + "EffectIds:" + Luban.StringUtil.CollectionToString(EffectIds) + ","
        + "ImagePath:" + ImagePath + ","
        + "Frequency:" + Frequency + ","
        + "}";
    }
}

}

