
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using TEngine.Localization.SimpleJSON;



namespace GameConfig
{
public sealed partial class TableStageMidReward : Luban.BeanBase
{
    public TableStageMidReward(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = _buf["Type"]; }
        { if(!_buf["Des"].IsString) { throw new SerializationException(); }  Des = _buf["Des"]; }
        { var __json0 = _buf["Params"]; if(!__json0.IsArray) { throw new SerializationException(); } Params = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Params.Add(__v0); }   }
        { if(!_buf["Weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["Weight"]; }
        { if(!_buf["SpriteIndex"].IsNumber) { throw new SerializationException(); }  SpriteIndex = _buf["SpriteIndex"]; }
    }

    public static TableStageMidReward DeserializeTableStageMidReward(JSONNode _buf)
    {
        return new TableStageMidReward(_buf);
    }

    public readonly int Id;
    public readonly int Type;
    /// <summary>
    /// 奖励关卡描述
    /// </summary>
    public readonly string Des;
    /// <summary>
    /// 参数
    /// </summary>
    public readonly System.Collections.Generic.List<int> Params;
    /// <summary>
    /// 权重
    /// </summary>
    public readonly int Weight;
    /// <summary>
    /// 图片索引
    /// </summary>
    public readonly int SpriteIndex;
   
    public const int __ID__ = 1719203207;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef()
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Type:" + Type + ","
        + "Des:" + Des + ","
        + "Params:" + Luban.StringUtil.CollectionToString(Params) + ","
        + "Weight:" + Weight + ","
        + "SpriteIndex:" + SpriteIndex + ","
        + "}";
    }
}

}

