
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using TEngine.Localization.SimpleJSON;



namespace GameConfig
{
public sealed partial class TableLightData : Luban.BeanBase
{
    public TableLightData(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Initial"].IsNumber) { throw new SerializationException(); }  Initial = _buf["Initial"]; }
        { if(!_buf["Target"].IsNumber) { throw new SerializationException(); }  Target = _buf["Target"]; }
        { if(!_buf["Time"].IsNumber) { throw new SerializationException(); }  Time = _buf["Time"]; }
        { if(!_buf["InnerRadius"].IsNumber) { throw new SerializationException(); }  InnerRadius = _buf["InnerRadius"]; }
        { if(!_buf["OuterRadius"].IsNumber) { throw new SerializationException(); }  OuterRadius = _buf["OuterRadius"]; }
    }

    public static TableLightData DeserializeTableLightData(JSONNode _buf)
    {
        return new TableLightData(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 初始强度
    /// </summary>
    public readonly float Initial;
    /// <summary>
    /// 目标强度
    /// </summary>
    public readonly float Target;
    /// <summary>
    /// 过渡时间
    /// </summary>
    public readonly float Time;
    /// <summary>
    /// 点光源内半径
    /// </summary>
    public readonly float InnerRadius;
    /// <summary>
    /// 点光源外半径
    /// </summary>
    public readonly float OuterRadius;
   
    public const int __ID__ = 1076573650;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef()
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Initial:" + Initial + ","
        + "Target:" + Target + ","
        + "Time:" + Time + ","
        + "InnerRadius:" + InnerRadius + ","
        + "OuterRadius:" + OuterRadius + ","
        + "}";
    }
}

}

