
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using TEngine.Localization.SimpleJSON;



namespace GameConfig
{
public sealed partial class TableGridItem : Luban.BeanBase
{
    public TableGridItem(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Des"].IsString) { throw new SerializationException(); }  Des = _buf["Des"]; }
        { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = _buf["Type"]; }
        { if(!_buf["Level"].IsNumber) { throw new SerializationException(); }  Level = _buf["Level"]; }
        { if(!_buf["UpgradeNum"].IsNumber) { throw new SerializationException(); }  UpgradeNum = _buf["UpgradeNum"]; }
        { var __json0 = _buf["Size"]; if(!__json0.IsArray) { throw new SerializationException(); } Size = new System.Collections.Generic.List<System.Collections.Generic.List<int>>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { System.Collections.Generic.List<int> __v0;  { var __json1 = __e0; if(!__json1.IsArray) { throw new SerializationException(); } __v0 = new System.Collections.Generic.List<int>(__json1.Count); foreach(JSONNode __e1 in __json1.Children) { int __v1;  { if(!__e1.IsNumber) { throw new SerializationException(); }  __v1 = __e1; }  __v0.Add(__v1); }   }  Size.Add(__v0); }   }
        { if(!_buf["Icon"].IsString) { throw new SerializationException(); }  Icon = _buf["Icon"]; }
        { if(!_buf["IconOutLine"].IsString) { throw new SerializationException(); }  IconOutLine = _buf["IconOutLine"]; }
        { var __json0 = _buf["EffectcellsPosition"]; if(!__json0.IsArray) { throw new SerializationException(); } EffectcellsPosition = new System.Collections.Generic.List<System.Collections.Generic.List<int>>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { System.Collections.Generic.List<int> __v0;  { var __json1 = __e0; if(!__json1.IsArray) { throw new SerializationException(); } __v0 = new System.Collections.Generic.List<int>(__json1.Count); foreach(JSONNode __e1 in __json1.Children) { int __v1;  { if(!__e1.IsNumber) { throw new SerializationException(); }  __v1 = __e1; }  __v0.Add(__v1); }   }  EffectcellsPosition.Add(__v0); }   }
        { if(!_buf["Price"].IsNumber) { throw new SerializationException(); }  Price = _buf["Price"]; }
        { var __json0 = _buf["Access"]; if(!__json0.IsArray) { throw new SerializationException(); } Access = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Access.Add(__v0); }   }
        { var __json0 = _buf["Tag"]; if(!__json0.IsArray) { throw new SerializationException(); } Tag = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Tag.Add(__v0); }   }
    }

    public static TableGridItem DeserializeTableGridItem(JSONNode _buf)
    {
        return new TableGridItem(_buf);
    }

    /// <summary>
    /// 背包物品编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 背包物品名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 背包物品描述
    /// </summary>
    public readonly string Des;
    /// <summary>
    /// 物品类型(去对应表找相同Id的数据)
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 稀有度
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 升级后的物品Id
    /// </summary>
    public readonly int UpgradeNum;
    /// <summary>
    /// 形状大小
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<int>> Size;
    /// <summary>
    /// 图片路径
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 描边图片路径
    /// </summary>
    public readonly string IconOutLine;
    /// <summary>
    /// （暂时不用）漂流物影响范围（漂流物专属）
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<int>> EffectcellsPosition;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 获取方式
    /// </summary>
    public readonly System.Collections.Generic.List<int> Access;
    /// <summary>
    /// 标签（影响刷新概率）
    /// </summary>
    public readonly System.Collections.Generic.List<int> Tag;
   
    public const int __ID__ = -778008249;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef()
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Des:" + Des + ","
        + "Type:" + Type + ","
        + "Level:" + Level + ","
        + "UpgradeNum:" + UpgradeNum + ","
        + "Size:" + Luban.StringUtil.CollectionToString(Size) + ","
        + "Icon:" + Icon + ","
        + "IconOutLine:" + IconOutLine + ","
        + "EffectcellsPosition:" + Luban.StringUtil.CollectionToString(EffectcellsPosition) + ","
        + "Price:" + Price + ","
        + "Access:" + Luban.StringUtil.CollectionToString(Access) + ","
        + "Tag:" + Luban.StringUtil.CollectionToString(Tag) + ","
        + "}";
    }
}

}

