
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using TEngine.Localization.SimpleJSON;



namespace GameConfig
{
public sealed partial class TableGlobalVariable : Luban.BeanBase
{
    public TableGlobalVariable(JSONNode _buf) 
    {
        { if(!_buf["Key"].IsNumber) { throw new SerializationException(); }  Key = _buf["Key"]; }
        { if(!_buf["Value"].IsNumber) { throw new SerializationException(); }  Value = _buf["Value"]; }
    }

    public static TableGlobalVariable DeserializeTableGlobalVariable(JSONNode _buf)
    {
        return new TableGlobalVariable(_buf);
    }

    public readonly int Key;
    public readonly float Value;
   
    public const int __ID__ = -457247091;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef()
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Key:" + Key + ","
        + "Value:" + Value + ","
        + "}";
    }
}

}

