
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using TEngine.Localization.SimpleJSON;



namespace GameConfig
{
public sealed partial class TableLevel : Luban.BeanBase
{
    public TableLevel(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { var __json0 = _buf["MaxExp"]; if(!__json0.IsArray) { throw new SerializationException(); } MaxExp = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  MaxExp.Add(__v0); }   }
    }

    public static TableLevel DeserializeTableLevel(JSONNode _buf)
    {
        return new TableLevel(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 每级所需经验
    /// </summary>
    public readonly System.Collections.Generic.List<int> MaxExp;
   
    public const int __ID__ = 471039094;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef()
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "MaxExp:" + Luban.StringUtil.CollectionToString(MaxExp) + ","
        + "}";
    }
}

}

