
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using TEngine.Localization.SimpleJSON;



namespace GameConfig
{
public sealed partial class TableSound : Luban.BeanBase
{
    public TableSound(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Group"].IsNumber) { throw new SerializationException(); }  Group = _buf["Group"]; }
        { if(!_buf["SoundType"].IsNumber) { throw new SerializationException(); }  SoundType = _buf["SoundType"]; }
        { if(!_buf["SoundPath"].IsString) { throw new SerializationException(); }  SoundPath = _buf["SoundPath"]; }
    }

    public static TableSound DeserializeTableSound(JSONNode _buf)
    {
        return new TableSound(_buf);
    }

    public readonly int Id;
    public readonly int Group;
    public readonly int SoundType;
    public readonly string SoundPath;
   
    public const int __ID__ = 477800961;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef()
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Group:" + Group + ","
        + "SoundType:" + SoundType + ","
        + "SoundPath:" + SoundPath + ","
        + "}";
    }
}

}

