
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using TEngine.Localization.SimpleJSON;



namespace GameConfig
{
public sealed partial class TableEquipment : Luban.BeanBase
{
    public TableEquipment(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = _buf["Type"]; }
        { var __json0 = _buf["TraitType"]; if(!__json0.IsArray) { throw new SerializationException(); } TraitType = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  TraitType.Add(__v0); }   }
        { var __json0 = _buf["AttributeIds"]; if(!__json0.IsArray) { throw new SerializationException(); } AttributeIds = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  AttributeIds.Add(__v0); }   }
        { if(!_buf["FightPrefabPath"].IsString) { throw new SerializationException(); }  FightPrefabPath = _buf["FightPrefabPath"]; }
        { if(!_buf["Damage"].IsNumber) { throw new SerializationException(); }  Damage = _buf["Damage"]; }
        { if(!_buf["Repel"].IsNumber) { throw new SerializationException(); }  Repel = _buf["Repel"]; }
        { if(!_buf["CriticalEfficiency"].IsNumber) { throw new SerializationException(); }  CriticalEfficiency = _buf["CriticalEfficiency"]; }
        { if(!_buf["AttackRange"].IsNumber) { throw new SerializationException(); }  AttackRange = _buf["AttackRange"]; }
        { if(!_buf["AttackCool"].IsNumber) { throw new SerializationException(); }  AttackCool = _buf["AttackCool"]; }
        { if(!_buf["Shield"].IsNumber) { throw new SerializationException(); }  Shield = _buf["Shield"]; }
        { if(!_buf["ShieldCool"].IsNumber) { throw new SerializationException(); }  ShieldCool = _buf["ShieldCool"]; }
    }

    public static TableEquipment DeserializeTableEquipment(JSONNode _buf)
    {
        return new TableEquipment(_buf);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 装备类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 羁绊
    /// </summary>
    public readonly System.Collections.Generic.List<int> TraitType;
    /// <summary>
    /// 初始词条
    /// </summary>
    public readonly System.Collections.Generic.List<int> AttributeIds;
    /// <summary>
    /// 预制体路径
    /// </summary>
    public readonly string FightPrefabPath;
    /// <summary>
    /// 基础伤害
    /// </summary>
    public readonly int Damage;
    /// <summary>
    /// 击退
    /// </summary>
    public readonly float Repel;
    /// <summary>
    /// 暴击效率
    /// </summary>
    public readonly int CriticalEfficiency;
    /// <summary>
    /// 攻击范围
    /// </summary>
    public readonly float AttackRange;
    /// <summary>
    /// 攻击间隔
    /// </summary>
    public readonly float AttackCool;
    /// <summary>
    /// 护盾量
    /// </summary>
    public readonly int Shield;
    /// <summary>
    /// 护盾恢复间隔
    /// </summary>
    public readonly float ShieldCool;
   
    public const int __ID__ = 1467743616;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef()
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Type:" + Type + ","
        + "TraitType:" + Luban.StringUtil.CollectionToString(TraitType) + ","
        + "AttributeIds:" + Luban.StringUtil.CollectionToString(AttributeIds) + ","
        + "FightPrefabPath:" + FightPrefabPath + ","
        + "Damage:" + Damage + ","
        + "Repel:" + Repel + ","
        + "CriticalEfficiency:" + CriticalEfficiency + ","
        + "AttackRange:" + AttackRange + ","
        + "AttackCool:" + AttackCool + ","
        + "Shield:" + Shield + ","
        + "ShieldCool:" + ShieldCool + ","
        + "}";
    }
}

}

