
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using TEngine.Localization.SimpleJSON;



namespace GameConfig
{
public sealed partial class TableEquipmentEffect : Luban.BeanBase
{
    public TableEquipmentEffect(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Des"].IsString) { throw new SerializationException(); }  Des = _buf["Des"]; }
        { if(!_buf["TriggerTime"].IsNumber) { throw new SerializationException(); }  TriggerTime = _buf["TriggerTime"]; }
        { var __json0 = _buf["Condition"]; if(!__json0.IsArray) { throw new SerializationException(); } Condition = new System.Collections.Generic.List<System.Collections.Generic.List<System.Collections.Generic.List<int>>>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { System.Collections.Generic.List<System.Collections.Generic.List<int>> __v0;  { var __json1 = __e0; if(!__json1.IsArray) { throw new SerializationException(); } __v0 = new System.Collections.Generic.List<System.Collections.Generic.List<int>>(__json1.Count); foreach(JSONNode __e1 in __json1.Children) { System.Collections.Generic.List<int> __v1;  { var __json2 = __e1; if(!__json2.IsArray) { throw new SerializationException(); } __v1 = new System.Collections.Generic.List<int>(__json2.Count); foreach(JSONNode __e2 in __json2.Children) { int __v2;  { if(!__e2.IsNumber) { throw new SerializationException(); }  __v2 = __e2; }  __v1.Add(__v2); }   }  __v0.Add(__v1); }   }  Condition.Add(__v0); }   }
        { if(!_buf["TriggerCount"].IsNumber) { throw new SerializationException(); }  TriggerCount = _buf["TriggerCount"]; }
        { var __json0 = _buf["EffectType"]; if(!__json0.IsArray) { throw new SerializationException(); } EffectType = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  EffectType.Add(__v0); }   }
        { var __json0 = _buf["EffectParameters"]; if(!__json0.IsArray) { throw new SerializationException(); } EffectParameters = new System.Collections.Generic.List<System.Collections.Generic.List<int>>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { System.Collections.Generic.List<int> __v0;  { var __json1 = __e0; if(!__json1.IsArray) { throw new SerializationException(); } __v0 = new System.Collections.Generic.List<int>(__json1.Count); foreach(JSONNode __e1 in __json1.Children) { int __v1;  { if(!__e1.IsNumber) { throw new SerializationException(); }  __v1 = __e1; }  __v0.Add(__v1); }   }  EffectParameters.Add(__v0); }   }
    }

    public static TableEquipmentEffect DeserializeTableEquipmentEffect(JSONNode _buf)
    {
        return new TableEquipmentEffect(_buf);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 效果名称（可以没有）
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 效果描述
    /// </summary>
    public readonly string Des;
    /// <summary>
    /// 触发时机
    /// </summary>
    public readonly int TriggerTime;
    /// <summary>
    /// 触发条件（且运算——必须满足所有条件）
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<System.Collections.Generic.List<int>>> Condition;
    /// <summary>
    /// 触发次数
    /// </summary>
    public readonly int TriggerCount;
    /// <summary>
    /// 效果类型
    /// </summary>
    public readonly System.Collections.Generic.List<int> EffectType;
    /// <summary>
    /// 效果参数
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<int>> EffectParameters;
   
    public const int __ID__ = 108233521;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef()
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Des:" + Des + ","
        + "TriggerTime:" + TriggerTime + ","
        + "Condition:" + Luban.StringUtil.CollectionToString(Condition) + ","
        + "TriggerCount:" + TriggerCount + ","
        + "EffectType:" + Luban.StringUtil.CollectionToString(EffectType) + ","
        + "EffectParameters:" + Luban.StringUtil.CollectionToString(EffectParameters) + ","
        + "}";
    }
}

}

