
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using TEngine.Localization.SimpleJSON;



namespace GameConfig
{
public sealed partial class TableEffect : Luban.BeanBase
{
    public TableEffect(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Des"].IsString) { throw new SerializationException(); }  Des = _buf["Des"]; }
        { var __json0 = _buf["TriggerTime"]; if(!__json0.IsArray) { throw new SerializationException(); } TriggerTime = new System.Collections.Generic.List<System.Collections.Generic.List<int>>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { System.Collections.Generic.List<int> __v0;  { var __json1 = __e0; if(!__json1.IsArray) { throw new SerializationException(); } __v0 = new System.Collections.Generic.List<int>(__json1.Count); foreach(JSONNode __e1 in __json1.Children) { int __v1;  { if(!__e1.IsNumber) { throw new SerializationException(); }  __v1 = __e1; }  __v0.Add(__v1); }   }  TriggerTime.Add(__v0); }   }
        { if(!_buf["ConditionType"].IsNumber) { throw new SerializationException(); }  ConditionType = _buf["ConditionType"]; }
        { var __json0 = _buf["Condition"]; if(!__json0.IsArray) { throw new SerializationException(); } Condition = new System.Collections.Generic.List<System.Collections.Generic.List<float>>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { System.Collections.Generic.List<float> __v0;  { var __json1 = __e0; if(!__json1.IsArray) { throw new SerializationException(); } __v0 = new System.Collections.Generic.List<float>(__json1.Count); foreach(JSONNode __e1 in __json1.Children) { float __v1;  { if(!__e1.IsNumber) { throw new SerializationException(); }  __v1 = __e1; }  __v0.Add(__v1); }   }  Condition.Add(__v0); }   }
        { var __json0 = _buf["MinValue"]; if(!__json0.IsArray) { throw new SerializationException(); } MinValue = new System.Collections.Generic.List<System.Collections.Generic.List<float>>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { System.Collections.Generic.List<float> __v0;  { var __json1 = __e0; if(!__json1.IsArray) { throw new SerializationException(); } __v0 = new System.Collections.Generic.List<float>(__json1.Count); foreach(JSONNode __e1 in __json1.Children) { float __v1;  { if(!__e1.IsNumber) { throw new SerializationException(); }  __v1 = __e1; }  __v0.Add(__v1); }   }  MinValue.Add(__v0); }   }
        { var __json0 = _buf["MaxValue"]; if(!__json0.IsArray) { throw new SerializationException(); } MaxValue = new System.Collections.Generic.List<System.Collections.Generic.List<float>>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { System.Collections.Generic.List<float> __v0;  { var __json1 = __e0; if(!__json1.IsArray) { throw new SerializationException(); } __v0 = new System.Collections.Generic.List<float>(__json1.Count); foreach(JSONNode __e1 in __json1.Children) { float __v1;  { if(!__e1.IsNumber) { throw new SerializationException(); }  __v1 = __e1; }  __v0.Add(__v1); }   }  MaxValue.Add(__v0); }   }
        { if(!_buf["TriggerType"].IsNumber) { throw new SerializationException(); }  TriggerType = _buf["TriggerType"]; }
        { if(!_buf["TriggerCount"].IsNumber) { throw new SerializationException(); }  TriggerCount = _buf["TriggerCount"]; }
        { if(!_buf["EffectType"].IsNumber) { throw new SerializationException(); }  EffectType = _buf["EffectType"]; }
        { if(!_buf["Probability"].IsNumber) { throw new SerializationException(); }  Probability = _buf["Probability"]; }
        { var __json0 = _buf["EffectParameters"]; if(!__json0.IsArray) { throw new SerializationException(); } EffectParameters = new System.Collections.Generic.List<System.Collections.Generic.List<float>>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { System.Collections.Generic.List<float> __v0;  { var __json1 = __e0; if(!__json1.IsArray) { throw new SerializationException(); } __v0 = new System.Collections.Generic.List<float>(__json1.Count); foreach(JSONNode __e1 in __json1.Children) { float __v1;  { if(!__e1.IsNumber) { throw new SerializationException(); }  __v1 = __e1; }  __v0.Add(__v1); }   }  EffectParameters.Add(__v0); }   }
    }

    public static TableEffect DeserializeTableEffect(JSONNode _buf)
    {
        return new TableEffect(_buf);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 效果名称（可以没有）
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 效果描述
    /// </summary>
    public readonly string Des;
    /// <summary>
    /// 触发时机
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<int>> TriggerTime;
    /// <summary>
    /// 参数统计方式
    /// </summary>
    public readonly int ConditionType;
    /// <summary>
    /// 触发条件（且运算——必须满足所有条件）
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<float>> Condition;
    /// <summary>
    /// Condition&gt;=MinValue
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<float>> MinValue;
    /// <summary>
    /// Condition&lt;=MinValue
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<float>> MaxValue;
    /// <summary>
    /// 触发次数类型
    /// </summary>
    public readonly int TriggerType;
    /// <summary>
    /// 触发次数
    /// </summary>
    public readonly int TriggerCount;
    /// <summary>
    /// 效果类型
    /// </summary>
    public readonly int EffectType;
    /// <summary>
    /// 触发概率(千分比)
    /// </summary>
    public readonly int Probability;
    /// <summary>
    /// 效果参数
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<float>> EffectParameters;
   
    public const int __ID__ = 1517352671;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef()
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Des:" + Des + ","
        + "TriggerTime:" + Luban.StringUtil.CollectionToString(TriggerTime) + ","
        + "ConditionType:" + ConditionType + ","
        + "Condition:" + Luban.StringUtil.CollectionToString(Condition) + ","
        + "MinValue:" + Luban.StringUtil.CollectionToString(MinValue) + ","
        + "MaxValue:" + Luban.StringUtil.CollectionToString(MaxValue) + ","
        + "TriggerType:" + TriggerType + ","
        + "TriggerCount:" + TriggerCount + ","
        + "EffectType:" + EffectType + ","
        + "Probability:" + Probability + ","
        + "EffectParameters:" + Luban.StringUtil.CollectionToString(EffectParameters) + ","
        + "}";
    }
}

}

