
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using TEngine.Localization.SimpleJSON;



namespace GameConfig
{
public sealed partial class TableStage : Luban.BeanBase
{
    public TableStage(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["LevelGroup"].IsNumber) { throw new SerializationException(); }  LevelGroup = _buf["LevelGroup"]; }
        { if(!_buf["MapId"].IsNumber) { throw new SerializationException(); }  MapId = _buf["MapId"]; }
        { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = _buf["Type"]; }
        { if(!_buf["Des"].IsString) { throw new SerializationException(); }  Des = _buf["Des"]; }
        { if(!_buf["BgmId"].IsNumber) { throw new SerializationException(); }  BgmId = _buf["BgmId"]; }
        { if(!_buf["StageTotalDuration"].IsNumber) { throw new SerializationException(); }  StageTotalDuration = _buf["StageTotalDuration"]; }
        { if(!_buf["DayTime"].IsNumber) { throw new SerializationException(); }  DayTime = _buf["DayTime"]; }
        { if(!_buf["DaySubTime"].IsNumber) { throw new SerializationException(); }  DaySubTime = _buf["DaySubTime"]; }
        { if(!_buf["DayMinTime"].IsNumber) { throw new SerializationException(); }  DayMinTime = _buf["DayMinTime"]; }
        { if(!_buf["NightTime"].IsNumber) { throw new SerializationException(); }  NightTime = _buf["NightTime"]; }
        { if(!_buf["NeighAddTime"].IsNumber) { throw new SerializationException(); }  NeighAddTime = _buf["NeighAddTime"]; }
        { if(!_buf["NightMaxTime"].IsNumber) { throw new SerializationException(); }  NightMaxTime = _buf["NightMaxTime"]; }
        { var __json0 = _buf["CubeAwardsTime"]; if(!__json0.IsArray) { throw new SerializationException(); } CubeAwardsTime = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  CubeAwardsTime.Add(__v0); }   }
        { var __json0 = _buf["GroupsData"]; if(!__json0.IsArray) { throw new SerializationException(); } GroupsData = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  GroupsData.Add(__v0); }   }
        { if(!_buf["MaxEnemies"].IsNumber) { throw new SerializationException(); }  MaxEnemies = _buf["MaxEnemies"]; }
    }

    public static TableStage DeserializeTableStage(JSONNode _buf)
    {
        return new TableStage(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 第几关
    /// </summary>
    public readonly int LevelGroup;
    /// <summary>
    /// 地图
    /// </summary>
    public readonly int MapId;
    /// <summary>
    /// 关卡类型（关卡图标索引）
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 关卡描述
    /// </summary>
    public readonly string Des;
    /// <summary>
    /// TableSound.Id
    /// </summary>
    public readonly int BgmId;
    /// <summary>
    /// 关卡最短时长，时间到了开启传送门
    /// </summary>
    public readonly int StageTotalDuration;
    /// <summary>
    /// 白天时间
    /// </summary>
    public readonly int DayTime;
    /// <summary>
    /// 白天衰减时间
    /// </summary>
    public readonly int DaySubTime;
    /// <summary>
    /// 白天最小时间
    /// </summary>
    public readonly int DayMinTime;
    /// <summary>
    /// 夜晚时间
    /// </summary>
    public readonly int NightTime;
    /// <summary>
    /// 夜晚增加时间
    /// </summary>
    public readonly int NeighAddTime;
    /// <summary>
    /// 黑夜最长时间
    /// </summary>
    public readonly int NightMaxTime;
    /// <summary>
    /// 三次魔方奖励节点
    /// </summary>
    public readonly System.Collections.Generic.List<int> CubeAwardsTime;
    /// <summary>
    /// 怪物组数据
    /// </summary>
    public readonly System.Collections.Generic.List<int> GroupsData;
    /// <summary>
    /// 最大怪物数量
    /// </summary>
    public readonly int MaxEnemies;
   
    public const int __ID__ = 477930480;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef()
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "LevelGroup:" + LevelGroup + ","
        + "MapId:" + MapId + ","
        + "Type:" + Type + ","
        + "Des:" + Des + ","
        + "BgmId:" + BgmId + ","
        + "StageTotalDuration:" + StageTotalDuration + ","
        + "DayTime:" + DayTime + ","
        + "DaySubTime:" + DaySubTime + ","
        + "DayMinTime:" + DayMinTime + ","
        + "NightTime:" + NightTime + ","
        + "NeighAddTime:" + NeighAddTime + ","
        + "NightMaxTime:" + NightMaxTime + ","
        + "CubeAwardsTime:" + Luban.StringUtil.CollectionToString(CubeAwardsTime) + ","
        + "GroupsData:" + Luban.StringUtil.CollectionToString(GroupsData) + ","
        + "MaxEnemies:" + MaxEnemies + ","
        + "}";
    }
}

}

