
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GameConfig
{

public interface ITable
{
    void _LoadData();
}

public partial class Tables
{
    public UI.TbUIWnd TbUIWnd {get; }
    public TbCommonSkill TbCommonSkill {get; }
    public TbCondition TbCondition {get; }
    public TbConstant TbConstant {get; }
    public TbEnemyAttr TbEnemyAttr {get; }
    public TbEnemyGroup TbEnemyGroup {get; }
    public TbEnemyUnit TbEnemyUnit {get; }
    public TbRoleBuff TbRoleBuff {get; }
    public TbRoleSkill TbRoleSkill {get; }
    public TbRoleStat TbRoleStat {get; }
    public TbRoleTrait TbRoleTrait {get; }
    public TbStatAugmentsData TbStatAugmentsData {get; }
    public TbTableEffect TbTableEffect {get; }
    public TbTableEquipment TbTableEquipment {get; }
    public TbTableEquipmentEffect TbTableEquipmentEffect {get; }
    public TbTableGlobalVariable TbTableGlobalVariable {get; }
    public TbTableGridItem TbTableGridItem {get; }
    public TbTableHextech TbTableHextech {get; }
    public TbTableLevel TbTableLevel {get; }
    public TbTableLightData TbTableLightData {get; }
    public TbTableSound TbTableSound {get; }
    public TbTableStage TbTableStage {get; }
    public TbTableStageMidReward TbTableStageMidReward {get; }

    public Tables(){}
    
    private void ResolveRef()
    {
        
    }
}

}
