
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using UnityEngine;
using TEngine.Localization.SimpleJSON;


namespace GameConfig
{
public partial class TbConstant : ITable
{
    private readonly System.Collections.Generic.Dictionary<int, Constant> _dataMap;
    private readonly System.Collections.Generic.List<Constant> _dataList;
    
    public TbConstant()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Constant>();
        _dataList = new System.Collections.Generic.List<Constant>();
    }

    public System.Collections.Generic.Dictionary<int, Constant> DataMap => _dataMap;
    public System.Collections.Generic.List<Constant> DataList => _dataList;

    public Constant GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Constant Get(int key) => _dataMap[key];
    public Constant this[int key] => _dataMap[key];


    public void _LoadData()
    {
        
        JSONNode _buf = JSON.Parse(GetJson("tbconstant"));
        foreach(JSONNode _ele in _buf.Children)
        {
            Constant _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::GameConfig.Constant.DeserializeConstant(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
            _v.ResolveRef();
        }
    }

    private string GetJson(string fileName)
    {
        var textAsset = GameModule.Resource.LoadAsset<TextAsset>(fileName);
        return textAsset.text;
    }
}

}

