
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using UnityEngine;
using TEngine.Localization.SimpleJSON;


namespace GameConfig
{
public partial class TbCommonSkill : ITable
{
    private readonly System.Collections.Generic.Dictionary<int, CommonSkill> _dataMap;
    private readonly System.Collections.Generic.List<CommonSkill> _dataList;
    
    public TbCommonSkill()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, CommonSkill>();
        _dataList = new System.Collections.Generic.List<CommonSkill>();
    }

    public System.Collections.Generic.Dictionary<int, CommonSkill> DataMap => _dataMap;
    public System.Collections.Generic.List<CommonSkill> DataList => _dataList;

    public CommonSkill GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CommonSkill Get(int key) => _dataMap[key];
    public CommonSkill this[int key] => _dataMap[key];


    public void _LoadData()
    {
        
        JSONNode _buf = JSON.Parse(GetJson("tbcommonskill"));
        foreach(JSONNode _ele in _buf.Children)
        {
            CommonSkill _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::GameConfig.CommonSkill.DeserializeCommonSkill(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
            _v.ResolveRef();
        }
    }

    private string GetJson(string fileName)
    {
        var textAsset = GameModule.Resource.LoadAsset<TextAsset>(fileName);
        return textAsset.text;
    }
}

}

