
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using UnityEngine;
using TEngine.Localization.SimpleJSON;


namespace GameConfig
{
public partial class TbCondition : ITable
{
    private readonly System.Collections.Generic.Dictionary<int, Condition> _dataMap;
    private readonly System.Collections.Generic.List<Condition> _dataList;
    
    public TbCondition()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Condition>();
        _dataList = new System.Collections.Generic.List<Condition>();
    }

    public System.Collections.Generic.Dictionary<int, Condition> DataMap => _dataMap;
    public System.Collections.Generic.List<Condition> DataList => _dataList;

    public Condition GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Condition Get(int key) => _dataMap[key];
    public Condition this[int key] => _dataMap[key];


    public void _LoadData()
    {
        
        JSONNode _buf = JSON.Parse(GetJson("tbcondition"));
        foreach(JSONNode _ele in _buf.Children)
        {
            Condition _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::GameConfig.Condition.DeserializeCondition(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
            _v.ResolveRef();
        }
    }

    private string GetJson(string fileName)
    {
        var textAsset = GameModule.Resource.LoadAsset<TextAsset>(fileName);
        return textAsset.text;
    }
}

}

