
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using UnityEngine;
using TEngine.Localization.SimpleJSON;


namespace GameConfig
{
public partial class TbEnemyUnit : ITable
{
    private readonly System.Collections.Generic.Dictionary<int, EnemyUnit> _dataMap;
    private readonly System.Collections.Generic.List<EnemyUnit> _dataList;
    
    public TbEnemyUnit()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, EnemyUnit>();
        _dataList = new System.Collections.Generic.List<EnemyUnit>();
    }

    public System.Collections.Generic.Dictionary<int, EnemyUnit> DataMap => _dataMap;
    public System.Collections.Generic.List<EnemyUnit> DataList => _dataList;

    public EnemyUnit GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public EnemyUnit Get(int key) => _dataMap[key];
    public EnemyUnit this[int key] => _dataMap[key];


    public void _LoadData()
    {
        
        JSONNode _buf = JSON.Parse(GetJson("tbenemyunit"));
        foreach(JSONNode _ele in _buf.Children)
        {
            EnemyUnit _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::GameConfig.EnemyUnit.DeserializeEnemyUnit(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
            _v.ResolveRef();
        }
    }

    private string GetJson(string fileName)
    {
        var textAsset = GameModule.Resource.LoadAsset<TextAsset>(fileName);
        return textAsset.text;
    }
}

}

