
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using UnityEngine;
using TEngine.Localization.SimpleJSON;


namespace GameConfig
{
public partial class TbEnemyAttr : ITable
{
    private readonly System.Collections.Generic.Dictionary<int, EnemyAttr> _dataMap;
    private readonly System.Collections.Generic.List<EnemyAttr> _dataList;
    
    public TbEnemyAttr()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, EnemyAttr>();
        _dataList = new System.Collections.Generic.List<EnemyAttr>();
    }

    public System.Collections.Generic.Dictionary<int, EnemyAttr> DataMap => _dataMap;
    public System.Collections.Generic.List<EnemyAttr> DataList => _dataList;

    public EnemyAttr GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public EnemyAttr Get(int key) => _dataMap[key];
    public EnemyAttr this[int key] => _dataMap[key];


    public void _LoadData()
    {
        
        JSONNode _buf = JSON.Parse(GetJson("tbenemyattr"));
        foreach(JSONNode _ele in _buf.Children)
        {
            EnemyAttr _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::GameConfig.EnemyAttr.DeserializeEnemyAttr(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
            _v.ResolveRef();
        }
    }

    private string GetJson(string fileName)
    {
        var textAsset = GameModule.Resource.LoadAsset<TextAsset>(fileName);
        return textAsset.text;
    }
}

}

