
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using UnityEngine;
using TEngine.Localization.SimpleJSON;


namespace GameConfig
{
public partial class TbEnemyGroup : ITable
{
    private readonly System.Collections.Generic.Dictionary<int, EnemyGroup> _dataMap;
    private readonly System.Collections.Generic.List<EnemyGroup> _dataList;
    
    public TbEnemyGroup()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, EnemyGroup>();
        _dataList = new System.Collections.Generic.List<EnemyGroup>();
    }

    public System.Collections.Generic.Dictionary<int, EnemyGroup> DataMap => _dataMap;
    public System.Collections.Generic.List<EnemyGroup> DataList => _dataList;

    public EnemyGroup GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public EnemyGroup Get(int key) => _dataMap[key];
    public EnemyGroup this[int key] => _dataMap[key];


    public void _LoadData()
    {
        
        JSONNode _buf = JSON.Parse(GetJson("tbenemygroup"));
        foreach(JSONNode _ele in _buf.Children)
        {
            EnemyGroup _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::GameConfig.EnemyGroup.DeserializeEnemyGroup(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
            _v.ResolveRef();
        }
    }

    private string GetJson(string fileName)
    {
        var textAsset = GameModule.Resource.LoadAsset<TextAsset>(fileName);
        return textAsset.text;
    }
}

}

