
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using UnityEngine;
using TEngine.Localization.SimpleJSON;


namespace GameConfig
{
public partial class TbRoleSkill : ITable
{
    private readonly System.Collections.Generic.Dictionary<int, RoleSkill> _dataMap;
    private readonly System.Collections.Generic.List<RoleSkill> _dataList;
    
    public TbRoleSkill()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, RoleSkill>();
        _dataList = new System.Collections.Generic.List<RoleSkill>();
    }

    public System.Collections.Generic.Dictionary<int, RoleSkill> DataMap => _dataMap;
    public System.Collections.Generic.List<RoleSkill> DataList => _dataList;

    public RoleSkill GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public RoleSkill Get(int key) => _dataMap[key];
    public RoleSkill this[int key] => _dataMap[key];


    public void _LoadData()
    {
        
        JSONNode _buf = JSON.Parse(GetJson("tbroleskill"));
        foreach(JSONNode _ele in _buf.Children)
        {
            RoleSkill _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::GameConfig.RoleSkill.DeserializeRoleSkill(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
            _v.ResolveRef();
        }
    }

    private string GetJson(string fileName)
    {
        var textAsset = GameModule.Resource.LoadAsset<TextAsset>(fileName);
        return textAsset.text;
    }
}

}

