
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using UnityEngine;
using TEngine.Localization.SimpleJSON;


namespace GameConfig
{
public partial class TbRoleStat : ITable
{
    private readonly System.Collections.Generic.Dictionary<int, RoleStat> _dataMap;
    private readonly System.Collections.Generic.List<RoleStat> _dataList;
    
    public TbRoleStat()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, RoleStat>();
        _dataList = new System.Collections.Generic.List<RoleStat>();
    }

    public System.Collections.Generic.Dictionary<int, RoleStat> DataMap => _dataMap;
    public System.Collections.Generic.List<RoleStat> DataList => _dataList;

    public RoleStat GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public RoleStat Get(int key) => _dataMap[key];
    public RoleStat this[int key] => _dataMap[key];


    public void _LoadData()
    {
        
        JSONNode _buf = JSON.Parse(GetJson("tbrolestat"));
        foreach(JSONNode _ele in _buf.Children)
        {
            RoleStat _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::GameConfig.RoleStat.DeserializeRoleStat(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
            _v.ResolveRef();
        }
    }

    private string GetJson(string fileName)
    {
        var textAsset = GameModule.Resource.LoadAsset<TextAsset>(fileName);
        return textAsset.text;
    }
}

}

