
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using UnityEngine;
using TEngine.Localization.SimpleJSON;


namespace GameConfig
{
public partial class TbRoleTrait : ITable
{
    private readonly System.Collections.Generic.Dictionary<int, RoleTrait> _dataMap;
    private readonly System.Collections.Generic.List<RoleTrait> _dataList;
    
    public TbRoleTrait()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, RoleTrait>();
        _dataList = new System.Collections.Generic.List<RoleTrait>();
    }

    public System.Collections.Generic.Dictionary<int, RoleTrait> DataMap => _dataMap;
    public System.Collections.Generic.List<RoleTrait> DataList => _dataList;

    public RoleTrait GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public RoleTrait Get(int key) => _dataMap[key];
    public RoleTrait this[int key] => _dataMap[key];


    public void _LoadData()
    {
        
        JSONNode _buf = JSON.Parse(GetJson("tbroletrait"));
        foreach(JSONNode _ele in _buf.Children)
        {
            RoleTrait _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::GameConfig.RoleTrait.DeserializeRoleTrait(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
            _v.ResolveRef();
        }
    }

    private string GetJson(string fileName)
    {
        var textAsset = GameModule.Resource.LoadAsset<TextAsset>(fileName);
        return textAsset.text;
    }
}

}

