
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using UnityEngine;
using TEngine.Localization.SimpleJSON;


namespace GameConfig
{
public partial class TbRoleBuff : ITable
{
    private readonly System.Collections.Generic.Dictionary<int, RoleBuff> _dataMap;
    private readonly System.Collections.Generic.List<RoleBuff> _dataList;
    
    public TbRoleBuff()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, RoleBuff>();
        _dataList = new System.Collections.Generic.List<RoleBuff>();
    }

    public System.Collections.Generic.Dictionary<int, RoleBuff> DataMap => _dataMap;
    public System.Collections.Generic.List<RoleBuff> DataList => _dataList;

    public RoleBuff GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public RoleBuff Get(int key) => _dataMap[key];
    public RoleBuff this[int key] => _dataMap[key];


    public void _LoadData()
    {
        
        JSONNode _buf = JSON.Parse(GetJson("tbrolebuff"));
        foreach(JSONNode _ele in _buf.Children)
        {
            RoleBuff _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::GameConfig.RoleBuff.DeserializeRoleBuff(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
            _v.ResolveRef();
        }
    }

    private string GetJson(string fileName)
    {
        var textAsset = GameModule.Resource.LoadAsset<TextAsset>(fileName);
        return textAsset.text;
    }
}

}

