
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using UnityEngine;
using TEngine.Localization.SimpleJSON;


namespace GameConfig
{
public partial class TbStatAugmentsData : ITable
{
    private readonly System.Collections.Generic.Dictionary<int, StatAugmentsData> _dataMap;
    private readonly System.Collections.Generic.List<StatAugmentsData> _dataList;
    
    public TbStatAugmentsData()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, StatAugmentsData>();
        _dataList = new System.Collections.Generic.List<StatAugmentsData>();
    }

    public System.Collections.Generic.Dictionary<int, StatAugmentsData> DataMap => _dataMap;
    public System.Collections.Generic.List<StatAugmentsData> DataList => _dataList;

    public StatAugmentsData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public StatAugmentsData Get(int key) => _dataMap[key];
    public StatAugmentsData this[int key] => _dataMap[key];


    public void _LoadData()
    {
        
        JSONNode _buf = JSON.Parse(GetJson("tbstataugmentsdata"));
        foreach(JSONNode _ele in _buf.Children)
        {
            StatAugmentsData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::GameConfig.StatAugmentsData.DeserializeStatAugmentsData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
            _v.ResolveRef();
        }
    }

    private string GetJson(string fileName)
    {
        var textAsset = GameModule.Resource.LoadAsset<TextAsset>(fileName);
        return textAsset.text;
    }
}

}

