
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using UnityEngine;
using TEngine.Localization.SimpleJSON;


namespace GameConfig
{
public partial class TbTableGridItem : ITable
{
    private readonly System.Collections.Generic.Dictionary<int, TableGridItem> _dataMap;
    private readonly System.Collections.Generic.List<TableGridItem> _dataList;
    
    public TbTableGridItem()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TableGridItem>();
        _dataList = new System.Collections.Generic.List<TableGridItem>();
    }

    public System.Collections.Generic.Dictionary<int, TableGridItem> DataMap => _dataMap;
    public System.Collections.Generic.List<TableGridItem> DataList => _dataList;

    public TableGridItem GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TableGridItem Get(int key) => _dataMap[key];
    public TableGridItem this[int key] => _dataMap[key];


    public void _LoadData()
    {
        
        JSONNode _buf = JSON.Parse(GetJson("tbtablegriditem"));
        foreach(JSONNode _ele in _buf.Children)
        {
            TableGridItem _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::GameConfig.TableGridItem.DeserializeTableGridItem(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
            _v.ResolveRef();
        }
    }

    private string GetJson(string fileName)
    {
        var textAsset = GameModule.Resource.LoadAsset<TextAsset>(fileName);
        return textAsset.text;
    }
}

}

