
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using UnityEngine;
using TEngine.Localization.SimpleJSON;


namespace GameConfig
{
public partial class TbTableEquipmentEffect : ITable
{
    private readonly System.Collections.Generic.Dictionary<int, TableEquipmentEffect> _dataMap;
    private readonly System.Collections.Generic.List<TableEquipmentEffect> _dataList;
    
    public TbTableEquipmentEffect()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TableEquipmentEffect>();
        _dataList = new System.Collections.Generic.List<TableEquipmentEffect>();
    }

    public System.Collections.Generic.Dictionary<int, TableEquipmentEffect> DataMap => _dataMap;
    public System.Collections.Generic.List<TableEquipmentEffect> DataList => _dataList;

    public TableEquipmentEffect GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TableEquipmentEffect Get(int key) => _dataMap[key];
    public TableEquipmentEffect this[int key] => _dataMap[key];


    public void _LoadData()
    {
        
        JSONNode _buf = JSON.Parse(GetJson("tbtableequipmenteffect"));
        foreach(JSONNode _ele in _buf.Children)
        {
            TableEquipmentEffect _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::GameConfig.TableEquipmentEffect.DeserializeTableEquipmentEffect(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
            _v.ResolveRef();
        }
    }

    private string GetJson(string fileName)
    {
        var textAsset = GameModule.Resource.LoadAsset<TextAsset>(fileName);
        return textAsset.text;
    }
}

}

