
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using UnityEngine;
using TEngine.Localization.SimpleJSON;


namespace GameConfig
{
public partial class TbTableGlobalVariable : ITable
{
    private readonly System.Collections.Generic.Dictionary<int, TableGlobalVariable> _dataMap;
    private readonly System.Collections.Generic.List<TableGlobalVariable> _dataList;
    
    public TbTableGlobalVariable()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TableGlobalVariable>();
        _dataList = new System.Collections.Generic.List<TableGlobalVariable>();
    }

    public System.Collections.Generic.Dictionary<int, TableGlobalVariable> DataMap => _dataMap;
    public System.Collections.Generic.List<TableGlobalVariable> DataList => _dataList;

    public TableGlobalVariable GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TableGlobalVariable Get(int key) => _dataMap[key];
    public TableGlobalVariable this[int key] => _dataMap[key];


    public void _LoadData()
    {
        
        JSONNode _buf = JSON.Parse(GetJson("tbtableglobalvariable"));
        foreach(JSONNode _ele in _buf.Children)
        {
            TableGlobalVariable _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::GameConfig.TableGlobalVariable.DeserializeTableGlobalVariable(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
            _v.ResolveRef();
        }
    }

    private string GetJson(string fileName)
    {
        var textAsset = GameModule.Resource.LoadAsset<TextAsset>(fileName);
        return textAsset.text;
    }
}

}

