
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using UnityEngine;
using TEngine.Localization.SimpleJSON;


namespace GameConfig
{
public partial class TbTableEquipment : ITable
{
    private readonly System.Collections.Generic.Dictionary<int, TableEquipment> _dataMap;
    private readonly System.Collections.Generic.List<TableEquipment> _dataList;
    
    public TbTableEquipment()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TableEquipment>();
        _dataList = new System.Collections.Generic.List<TableEquipment>();
    }

    public System.Collections.Generic.Dictionary<int, TableEquipment> DataMap => _dataMap;
    public System.Collections.Generic.List<TableEquipment> DataList => _dataList;

    public TableEquipment GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TableEquipment Get(int key) => _dataMap[key];
    public TableEquipment this[int key] => _dataMap[key];


    public void _LoadData()
    {
        
        JSONNode _buf = JSON.Parse(GetJson("tbtableequipment"));
        foreach(JSONNode _ele in _buf.Children)
        {
            TableEquipment _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::GameConfig.TableEquipment.DeserializeTableEquipment(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
            _v.ResolveRef();
        }
    }

    private string GetJson(string fileName)
    {
        var textAsset = GameModule.Resource.LoadAsset<TextAsset>(fileName);
        return textAsset.text;
    }
}

}

