
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using UnityEngine;
using TEngine.Localization.SimpleJSON;


namespace GameConfig
{
public partial class TbTableHextech : ITable
{
    private readonly System.Collections.Generic.Dictionary<int, TableHextech> _dataMap;
    private readonly System.Collections.Generic.List<TableHextech> _dataList;
    
    public TbTableHextech()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TableHextech>();
        _dataList = new System.Collections.Generic.List<TableHextech>();
    }

    public System.Collections.Generic.Dictionary<int, TableHextech> DataMap => _dataMap;
    public System.Collections.Generic.List<TableHextech> DataList => _dataList;

    public TableHextech GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TableHextech Get(int key) => _dataMap[key];
    public TableHextech this[int key] => _dataMap[key];


    public void _LoadData()
    {
        
        JSONNode _buf = JSON.Parse(GetJson("tbtablehextech"));
        foreach(JSONNode _ele in _buf.Children)
        {
            TableHextech _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::GameConfig.TableHextech.DeserializeTableHextech(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
            _v.ResolveRef();
        }
    }

    private string GetJson(string fileName)
    {
        var textAsset = GameModule.Resource.LoadAsset<TextAsset>(fileName);
        return textAsset.text;
    }
}

}

