
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using UnityEngine;
using TEngine.Localization.SimpleJSON;


namespace GameConfig
{
public partial class TbTableLightData : ITable
{
    private readonly System.Collections.Generic.Dictionary<int, TableLightData> _dataMap;
    private readonly System.Collections.Generic.List<TableLightData> _dataList;
    
    public TbTableLightData()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TableLightData>();
        _dataList = new System.Collections.Generic.List<TableLightData>();
    }

    public System.Collections.Generic.Dictionary<int, TableLightData> DataMap => _dataMap;
    public System.Collections.Generic.List<TableLightData> DataList => _dataList;

    public TableLightData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TableLightData Get(int key) => _dataMap[key];
    public TableLightData this[int key] => _dataMap[key];


    public void _LoadData()
    {
        
        JSONNode _buf = JSON.Parse(GetJson("tbtablelightdata"));
        foreach(JSONNode _ele in _buf.Children)
        {
            TableLightData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::GameConfig.TableLightData.DeserializeTableLightData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
            _v.ResolveRef();
        }
    }

    private string GetJson(string fileName)
    {
        var textAsset = GameModule.Resource.LoadAsset<TextAsset>(fileName);
        return textAsset.text;
    }
}

}

