
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using UnityEngine;
using TEngine.Localization.SimpleJSON;


namespace GameConfig
{
public partial class TbTableSound : ITable
{
    private readonly System.Collections.Generic.Dictionary<int, TableSound> _dataMap;
    private readonly System.Collections.Generic.List<TableSound> _dataList;
    
    public TbTableSound()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TableSound>();
        _dataList = new System.Collections.Generic.List<TableSound>();
    }

    public System.Collections.Generic.Dictionary<int, TableSound> DataMap => _dataMap;
    public System.Collections.Generic.List<TableSound> DataList => _dataList;

    public TableSound GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TableSound Get(int key) => _dataMap[key];
    public TableSound this[int key] => _dataMap[key];


    public void _LoadData()
    {
        
        JSONNode _buf = JSON.Parse(GetJson("tbtablesound"));
        foreach(JSONNode _ele in _buf.Children)
        {
            TableSound _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::GameConfig.TableSound.DeserializeTableSound(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
            _v.ResolveRef();
        }
    }

    private string GetJson(string fileName)
    {
        var textAsset = GameModule.Resource.LoadAsset<TextAsset>(fileName);
        return textAsset.text;
    }
}

}

