
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using UnityEngine;
using TEngine.Localization.SimpleJSON;


namespace GameConfig
{
public partial class TbTableStageMidReward : ITable
{
    private readonly System.Collections.Generic.Dictionary<int, TableStageMidReward> _dataMap;
    private readonly System.Collections.Generic.List<TableStageMidReward> _dataList;
    
    public TbTableStageMidReward()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TableStageMidReward>();
        _dataList = new System.Collections.Generic.List<TableStageMidReward>();
    }

    public System.Collections.Generic.Dictionary<int, TableStageMidReward> DataMap => _dataMap;
    public System.Collections.Generic.List<TableStageMidReward> DataList => _dataList;

    public TableStageMidReward GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TableStageMidReward Get(int key) => _dataMap[key];
    public TableStageMidReward this[int key] => _dataMap[key];


    public void _LoadData()
    {
        
        JSONNode _buf = JSON.Parse(GetJson("tbtablestagemidreward"));
        foreach(JSONNode _ele in _buf.Children)
        {
            TableStageMidReward _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::GameConfig.TableStageMidReward.DeserializeTableStageMidReward(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
            _v.ResolveRef();
        }
    }

    private string GetJson(string fileName)
    {
        var textAsset = GameModule.Resource.LoadAsset<TextAsset>(fileName);
        return textAsset.text;
    }
}

}

