
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using UnityEngine;
using TEngine.Localization.SimpleJSON;


namespace GameConfig
{
public partial class TbTableEffect : ITable
{
    private readonly System.Collections.Generic.Dictionary<int, TableEffect> _dataMap;
    private readonly System.Collections.Generic.List<TableEffect> _dataList;
    
    public TbTableEffect()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TableEffect>();
        _dataList = new System.Collections.Generic.List<TableEffect>();
    }

    public System.Collections.Generic.Dictionary<int, TableEffect> DataMap => _dataMap;
    public System.Collections.Generic.List<TableEffect> DataList => _dataList;

    public TableEffect GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TableEffect Get(int key) => _dataMap[key];
    public TableEffect this[int key] => _dataMap[key];


    public void _LoadData()
    {
        
        JSONNode _buf = JSON.Parse(GetJson("tbtableeffect"));
        foreach(JSONNode _ele in _buf.Children)
        {
            TableEffect _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::GameConfig.TableEffect.DeserializeTableEffect(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
            _v.ResolveRef();
        }
    }

    private string GetJson(string fileName)
    {
        var textAsset = GameModule.Resource.LoadAsset<TextAsset>(fileName);
        return textAsset.text;
    }
}

}

