
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using UnityEngine;
using TEngine.Localization.SimpleJSON;


namespace GameConfig
{
public partial class TbTableStage : ITable
{
    private readonly System.Collections.Generic.Dictionary<int, TableStage> _dataMap;
    private readonly System.Collections.Generic.List<TableStage> _dataList;
    
    public TbTableStage()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TableStage>();
        _dataList = new System.Collections.Generic.List<TableStage>();
    }

    public System.Collections.Generic.Dictionary<int, TableStage> DataMap => _dataMap;
    public System.Collections.Generic.List<TableStage> DataList => _dataList;

    public TableStage GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TableStage Get(int key) => _dataMap[key];
    public TableStage this[int key] => _dataMap[key];


    public void _LoadData()
    {
        
        JSONNode _buf = JSON.Parse(GetJson("tbtablestage"));
        foreach(JSONNode _ele in _buf.Children)
        {
            TableStage _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::GameConfig.TableStage.DeserializeTableStage(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
            _v.ResolveRef();
        }
    }

    private string GetJson(string fileName)
    {
        var textAsset = GameModule.Resource.LoadAsset<TextAsset>(fileName);
        return textAsset.text;
    }
}

}

