
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using TEngine.Localization.SimpleJSON;



namespace GameConfig
{
public partial struct vector3int
{
    public vector3int(JSONNode _buf) 
    {
        { if(!_buf["x"].IsNumber) { throw new SerializationException(); }  X = _buf["x"]; }
        { if(!_buf["y"].IsNumber) { throw new SerializationException(); }  Y = _buf["y"]; }
        { if(!_buf["z"].IsNumber) { throw new SerializationException(); }  Z = _buf["z"]; }
    }

    public static vector3int Deserializevector3int(JSONNode _buf)
    {
        return new vector3int(_buf);
    }

    public readonly int X;
    public readonly int Y;
    public readonly int Z;
   

    public  void ResolveRef()
    {
    }

    public override string ToString()
    {
        return "{ "
        + "x:" + X + ","
        + "y:" + Y + ","
        + "z:" + Z + ","
        + "}";
    }
}

}

